In [ ]:
import sqlite3
import pandas as pd

# Connect to database
conn = sqlite3.connect('database/northwind.db')
cursor = conn.cursor()

# Check all tables - by cursor 
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())

# Check all table - by pandas
query = "SELECT * FROM Customers"
df = pd.read_sql_query(query, conn)
df.head()

[('Categories',), ('sqlite_sequence',), ('CustomerCustomerDemo',), ('CustomerDemographics',), ('Customers',), ('Employees',), ('EmployeeTerritories',), ('Order Details',), ('Orders',), ('Products',), ('Regions',), ('Shippers',), ('Suppliers',), ('Territories',)]

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [ ]:
# SELECT specific column
query = '''
SELECT CustomerID, CompanyName, Country
FROM Customers
'''
df = pd.read_sql_query(query, conn)
df

   CustomerID                         CompanyName  Country
0       ALFKI                 Alfreds Futterkiste  Germany
1       ANATR  Ana Trujillo Emparedados y helados   Mexico
2       ANTON             Antonio Moreno Taquería   Mexico
3       AROUT                     Around the Horn       UK
4       BERGS                  Berglunds snabbköp   Sweden
..        ...                                 ...      ...
88      WARTH                      Wartian Herkku  Finland
89      WELLI              Wellington Importadora   Brazil
90      WHITC                White Clover Markets      USA
91      WILMK                         Wilman Kala  Finland
92      WOLZA                      Wolski  Zajazd   Poland

[93 rows x 3 columns]

In [ ]:
# WHERE to filter value
query = '''
SELECT CustomerID, CompanyName, Country
FROM Customers
WHERE Country = 'Germany'
'''
df = pd.read_sql_query(query, conn)
df

   CustomerID               CompanyName  Country
0       ALFKI       Alfreds Futterkiste  Germany
1       BLAUS   Blauer See Delikatessen  Germany
2       WANDK         Die Wandernde Kuh  Germany
3       DRACD  Drachenblut Delikatessen  Germany
4       FRANK            Frankenversand  Germany
5       KOENE           Königlich Essen  Germany
6       LEHMS       Lehmanns Marktstand  Germany
7       MORGK    Morgenstern Gesundkost  Germany
8       OTTIK        Ottilies Käseladen  Germany
9       QUICK                QUICK-Stop  Germany
10      TOMSP        Toms Spezialitäten  Germany

In [ ]:
# ORDER BY to sort value
query = '''
SELECT CustomerID, CompanyName, Country
FROM Customers
WHERE Country = 'Germany'
ORDER BY CompanyName ASC
'''
df = pd.read_sql_query(query, conn)
df

   CustomerID               CompanyName  Country
0       ALFKI       Alfreds Futterkiste  Germany
1       BLAUS   Blauer See Delikatessen  Germany
2       WANDK         Die Wandernde Kuh  Germany
3       DRACD  Drachenblut Delikatessen  Germany
4       FRANK            Frankenversand  Germany
5       KOENE           Königlich Essen  Germany
6       LEHMS       Lehmanns Marktstand  Germany
7       MORGK    Morgenstern Gesundkost  Germany
8       OTTIK        Ottilies Käseladen  Germany
9       QUICK                QUICK-Stop  Germany
10      TOMSP        Toms Spezialitäten  Germany

In [ ]:
# LIMIT to limit rows
query = '''
SELECT CustomerID, CompanyName, Country
FROM Customers
WHERE Country = 'Germany'
ORDER BY CompanyName ASC
LIMIT 3
'''
df = pd.read_sql_query(query, conn)
df

  CustomerID              CompanyName  Country
0      ALFKI      Alfreds Futterkiste  Germany
1      BLAUS  Blauer See Delikatessen  Germany
2      WANDK        Die Wandernde Kuh  Germany

In [ ]:
# GROUP BY to grouped and conclude value
query = '''
SELECT Country, 
       COUNT(*) as TotalCustomers
FROM Customers
GROUP BY Country
ORDER BY TotalCustomers DESC
'''
df = pd.read_sql_query(query, conn)
df

        Country  TotalCustomers
0           USA              13
1       Germany              11
2        France              11
3        Brazil               9
4            UK               7
5         Spain               5
6        Mexico               5
7     Venezuela               4
8         Italy               3
9        Canada               3
10    Argentina               3
11  Switzerland               2
12       Sweden               2
13     Portugal               2
14      Finland               2
15      Denmark               2
16      Belgium               2
17      Austria               2
18          NaN               2
19       Poland               1
20       Norway               1
21      Ireland               1

In [ ]:
# หาว่าแต่ละ ShipCountry มี
# กี่ออเดอร์ -> COUNT(*)
# ค่าขนส่งรวม -> SUM(Freight)
# ค่าขนส่งเฉลี่ย -> AVG(Freight)
# เรียงจากค่าขนส่งรวมมากไปน้อย

query = '''
SELECT ShipCountry,
       COUNT(*) as TotalOrders,
       SUM(Freight) as TotalFreight,
       AVG(Freight) as AvgFreight
FROM Orders
GROUP BY ShipCountry
ORDER BY TotalFreight DESC
'''

df = pd.read_sql_query(query, conn)
df

    ShipCountry  TotalOrders  TotalFreight  AvgFreight
0           USA         2328     573251.00  246.241838
1       Germany         2193     537189.75  244.956566
2        France         1778     442055.75  248.625281
3        Brazil         1683     418464.50  248.642008
4            UK         1280     326250.00  254.882812
5        Mexico          899     228138.75  253.769466
6     Venezuela          707     174448.50  246.744696
7         Spain          691     172833.00  250.120116
8     Argentina          535     140088.50  261.847664
9        Canada          547     132277.00  241.822669
10        Italy          538     131315.25  244.080390
11       Sweden          391      95648.25  244.624680
12      Austria          380      93233.50  245.351316
13  Switzerland          367      92003.50  250.690736
14     Portugal          357      91889.00  257.392157
15      Denmark          352      90955.75  258.397017
16      Finland          369      89241.50  241.846883
17      Belgium          338      82943.75  245.395710
18       Poland          213      53669.25  251.968310
19       Norway          164      41288.00  251.756098
20      Ireland          172      40286.00  234.220930

In [ ]:
# JOIN to combine table
query = '''
SELECT Customers.CompanyName, Orders.OrderID, Orders.Freight
FROM Customers
JOIN Orders ON Customers.CustomerID = Orders.CustomerID
'''
df = pd.read_sql_query(query, conn)
df

                     CompanyName  OrderID  Freight
0      Vins et alcools Chevalier    10248    16.75
1             Toms Spezialitäten    10249    22.25
2                  Hanari Carnes    10250    25.00
3           Victuailles en stock    10251    20.25
4               Suprêmes délices    10252    36.25
...                          ...      ...      ...
16277       White Clover Markets    26525    42.50
16278             Wolski  Zajazd    26526   425.50
16279        Gourmet Lanchonetes    26527   280.00
16280   Blondesddsl père et fils    26528   131.25
16281            Du monde entier    26529   447.25

[16282 rows x 3 columns]

In [ ]:
# หาว่าแต่ละ CompanyName 
# มียอด Freight รวมเท่าไหร่ 
# เรียงจากมากไปน้อย 
# แสดงแค่ Top5
query = '''
SELECT CompanyName,
       SUM(Freight) as TotalFreight
FROM Customers
JOIN Orders
ON Customers.CustomerID = Orders.CustomerID
GROUP BY CompanyName
ORDER BY TotalFreight DESC
LIMIT 5
'''
df = pd.read_sql_query(query, conn)
df

                  CompanyName  TotalFreight
0                          IT      88488.75
1               B's Beverages      54797.25
2  Hungry Coyote Import Store      51597.00
3          Ricardo Adocicados      50285.25
4         Gourmet Lanchonetes      49939.00